/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zeynconverter;
import com.mycompany.zeynconverter.core.PreferencesService;

import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.JOptionPane;
import javax.swing.TransferHandler;
import javax.swing.SwingWorker;
import static javax.swing.TransferHandler.COPY;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
/**
 *
 * @author Zeyn
 */
public class MainFrame extends javax.swing.JFrame {

    //saving file data
    private List<File> conversionList = new ArrayList<>();
    private DefaultListModel<String> listModel = new DefaultListModel<>();
    private File outputFolder;
    private javax.swing.JLabel emptyListLabel;
    
    //prefs service instance
    private final PreferencesService prefsService = new PreferencesService();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {    
        initComponents();
        setLocationRelativeTo(null);
        listDisplay.setModel(listModel);
        pathTxtArea.setEditable(false);
        pathTxtArea.setLineWrap(true); //make the text wrapped
        pathTxtArea.setWrapStyleWord(true); //make the word wouldn't be cutten
        outputTxtField.setEditable(false);
        //show a friendly warn that there's still nothing added
        emptyListLabel = new javax.swing.JLabel("You are not added anything here :/");
        emptyListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emptyListLabel.setForeground(java.awt.Color.GRAY);
        
        //load the path from prefs service
        String savedPath = prefsService.loadPath();
        this.outputFolder = new File(savedPath);
        outputTxtField.setText(savedPath);
        
        listDisplay.setTransferHandler(fileDragHandler);
        emptyListLabel.setTransferHandler(fileDragHandler);
        
        
        //GUI list selection listener
        listDisplay.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Cek apakah perubahan sudah "final" dan ada item yang dipilih
                if (!e.getValueIsAdjusting()) {
                    int index = listDisplay.getSelectedIndex();

                    if (index != -1) {
                        // Ada item yang dipilih
                        // Ambil File dari "otak" data kita
                        File choosenFile = conversionList.get(index);
                        // Tampilkan path lengkapnya di pathTxtArea
                        pathTxtArea.setText(choosenFile.getAbsolutePath());
                    } else {
                        // Tidak ada item yang dipilih (misal setelah dihapus)
                        pathTxtArea.setText(""); // Kosongkan
                    }
                }
            }
        });
        
        updateListView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDisplay = new javax.swing.JList<>();
        appTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pathTxtArea = new javax.swing.JTextArea();
        pathLabel = new javax.swing.JLabel();
        addFileBtn = new javax.swing.JButton();
        deleteFileBtn = new javax.swing.JButton();
        upBtn = new javax.swing.JButton();
        downBtn = new javax.swing.JButton();
        convertBtn = new javax.swing.JButton();
        supportedInfo = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        outputTxtField = new javax.swing.JTextField();
        outputSetBtn = new javax.swing.JButton();
        progressLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        devNote = new javax.swing.JLabel();
        btnClearList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        listDisplay.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listDisplay);

        appTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        appTitle.setText("Zeyn Converter");

        pathTxtArea.setEditable(false);
        pathTxtArea.setColumns(20);
        pathTxtArea.setRows(5);
        jScrollPane3.setViewportView(pathTxtArea);

        pathLabel.setText("File Path");

        addFileBtn.setText("Add File(s)");
        addFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileBtnActionPerformed(evt);
            }
        });

        deleteFileBtn.setText("Delete from List");
        deleteFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFileBtnActionPerformed(evt);
            }
        });

        upBtn.setText("↑");
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });

        downBtn.setText("↓");
        downBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downBtnActionPerformed(evt);
            }
        });

        convertBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        convertBtn.setText("Convert");
        convertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertBtnActionPerformed(evt);
            }
        });

        supportedInfo.setText("*Curently Supported Format: only JPG (.jpg/.jpeg) and PNG (.png)");

        outputLabel.setText("Output Folder");

        outputTxtField.setEditable(false);
        outputTxtField.setText("<<Null>>");

        outputSetBtn.setText("Set Folder");
        outputSetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputSetBtnActionPerformed(evt);
            }
        });

        progressLabel.setText("Progress");

        progressBar.setForeground(new java.awt.Color(89, 168, 75));
        progressBar.setStringPainted(true);

        devNote.setText("(Currently, you may able to add WebP (.webp) files but it still won't work. The development on it under progress.)");

        btnClearList.setText("Clear List");
        btnClearList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(devNote)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(appTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(supportedInfo)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(outputLabel)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(outputTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(outputSetBtn))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pathLabel)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(upBtn)
                                            .addComponent(downBtn))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(addFileBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(deleteFileBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnClearList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressLabel)
                .addGap(284, 284, 284))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(outputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputSetBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pathLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addFileBtn)
                            .addComponent(upBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteFileBtn)
                            .addComponent(downBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearList)
                        .addGap(58, 58, 58)
                        .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(progressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supportedInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(devNote)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setMultiSelectionEnabled(true);
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "Gambar (JPG, PNG, WebP)", "jpg", "jpeg", "png", "webp");
        fileChooser.setFileFilter(filter);
        
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION){
            File[] files = fileChooser.getSelectedFiles();
            
            for (File file : files){
                conversionList.add(file);
                listModel.addElement(file.getName());
            }
            updateListView();
        }
    }//GEN-LAST:event_addFileBtnActionPerformed

    private void deleteFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFileBtnActionPerformed
        // TODO add your handling code here:
        //get all selected files
        int[] selectedIndices = listDisplay.getSelectedIndices();
        
        for (int i = selectedIndices.length -1; i>=0; i--){
            //get the index of selected files
            int index = selectedIndices[i];
            
            //removing from array list
            conversionList.remove(index);
            
            //removing selected files from GUI list
            listModel.remove(index);
        }
        updateListView();
    }//GEN-LAST:event_deleteFileBtnActionPerformed

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
        // TODO add your handling code here:
        //getting the selected index
        int index = listDisplay.getSelectedIndex();
        
        //checking is there a selected item or not
        if (index > 0) {
            //--- moving the data on the array list ---
            
            //get the file, then delete it from the current position
            File file = conversionList.remove(index);
            // insert it on a step above
            conversionList.add(index - 1, file);
            
            //--- moving the data on GUI list ---
            
            //get the file name and removing it from the current position
            String fileName = listModel.remove(index);
            
            // insert it on a step above
            listModel.add(index - 1, fileName);
            
            //keep the selection on the item while it was moved
            listDisplay.setSelectedIndex(index - 1);
        }
    }//GEN-LAST:event_upBtnActionPerformed

    private void downBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downBtnActionPerformed
        // TODO add your handling code here:
        //getting the selected index
        int index = listDisplay.getSelectedIndex();
        
        //checking is the selected was on the bottom and existed
        if (index != -1 && index < listModel.getSize() - 1) {
            //--- moving the data on the array list ---
            
            //get the file, then delete it from the current position
            File file = conversionList.remove(index);
            //insert on a step below
            conversionList.add(index + 1, file);
            
             //--- moving the data on GUI list ---
            
            //get the file name and removing it from the current position
            String fileName = listModel.remove(index);
            //insert on a step below
            listModel.add(index + 1, fileName);
            
            //keep the selection on the item while it was moved
            listDisplay.setSelectedIndex(index + 1);
        }
    }//GEN-LAST:event_downBtnActionPerformed

    private void convertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBtnActionPerformed
        // TODO add your handling code here:
        
        //checking is the list is empty or not
        if (conversionList.isEmpty()){
            JOptionPane.showMessageDialog(
                    this,
                    "You are not yet add anything here :/", 
                    "List is Empty",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //saving the file use JFileChooser
        JFileChooser saveChooser = new JFileChooser();
        saveChooser.setDialogTitle("Save PDF as...");
        saveChooser.setFileFilter(new FileNameExtensionFilter("PDF Document", "pdf"));
        
        //check is the output folder was set or not
        if(this.outputFolder != null){
            saveChooser.setCurrentDirectory(this.outputFolder);
        }
        
        int userSelection = saveChooser.showSaveDialog(this);
        
        //is user select "Save", not "Cancel"?
        if (userSelection == JFileChooser.APPROVE_OPTION){
            File fileToSave = saveChooser.getSelectedFile();
            
            //validating file name to ended with .pdf and its path
            String goalPath = fileToSave.getAbsolutePath();
            if(!goalPath.toLowerCase().endsWith(".pdf")){
                goalPath += ".pdf";
            }
            
            //--- CONVERSION PROCESS---
            
            //disabling all features
            convertBtn.setEnabled(false);
            addFileBtn.setEnabled(false);
            deleteFileBtn.setEnabled(false);
            upBtn.setEnabled(false);
            downBtn.setEnabled(false);
            outputSetBtn.setEnabled(false);
            listDisplay.setEnabled(false);
            btnClearList.setEnabled(false);
            
            //execute the converter method
            PdfConverterWorker worker = new PdfConverterWorker(conversionList, goalPath);
            worker.execute();
        }
    }//GEN-LAST:event_convertBtnActionPerformed

    private void outputSetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputSetBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser outputChooser = new JFileChooser();
        
        //set that JFileChooser only able to choose folder
        outputChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        outputChooser.setDialogTitle("Choose Output Folder");
        
        int result = outputChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION){
            //get the folder
            File selectedFolder = outputChooser.getSelectedFile();
            
            //save on outputFolder
            this.outputFolder = selectedFolder;
            
            //show the path on text field
            outputTxtField.setText(this.outputFolder.getAbsolutePath());
            
            //saving on prefs service
            prefsService.savePath(this.outputFolder.getAbsolutePath());
        }
    }//GEN-LAST:event_outputSetBtnActionPerformed

    private void btnClearListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearListActionPerformed
        // TODO add your handling code here:
        conversionList.clear();
        listModel.clear();
        updateListView();
    }//GEN-LAST:event_btnClearListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            // set look and feel to be like OS native view
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
                java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFileBtn;
    private javax.swing.JLabel appTitle;
    private javax.swing.JButton btnClearList;
    private javax.swing.JButton convertBtn;
    private javax.swing.JButton deleteFileBtn;
    private javax.swing.JLabel devNote;
    private javax.swing.JButton downBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listDisplay;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton outputSetBtn;
    private javax.swing.JTextField outputTxtField;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextArea pathTxtArea;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JLabel supportedInfo;
    private javax.swing.JButton upBtn;
    // End of variables declaration//GEN-END:variables

    //--- Drag and Drop Logic ---
    TransferHandler fileDragHandler = new TransferHandler(){
            @Override
            public boolean canImport(TransferHandler.TransferSupport support){
                //check is the dragged data was a "file list" or not
                if(!support.isDataFlavorSupported(DataFlavor.javaFileListFlavor)){
                    return false;
                }
                
                //tell OS to show "copy" icon
                support.setDropAction(COPY);
                return true;
            }
            
            @Override
            public boolean importData(TransferHandler.TransferSupport support){
                if(!canImport(support)){
                    return false;
                }
                
                Transferable t = support.getTransferable();
                
                try{
                    java.util.List<File> files = (java.util.List<File>) t.getTransferData(DataFlavor.javaFileListFlavor);
                    
                    for (File file : files){
                        String name = file.getName().toLowerCase();
                        
                        if (name.endsWith(".jpg") || name.endsWith(".jpeg") || name.endsWith(".png") || name.endsWith(".webp")){
                            if (!conversionList.contains(file)) {
                                conversionList.add(file);
                                listModel.addElement(file.getName());
                            }
                        }
                    }
                    updateListView();
                    return true;
                }catch (java.awt.datatransfer.UnsupportedFlavorException | java.io.IOException e){
                    e.printStackTrace();
                }
                return false;
            }
    };
    
    private void updateListView() {
        if (listModel.isEmpty()) {
            // Jika list kosong, tampilkan label di dalam scroll pane
            jScrollPane2.setViewportView(emptyListLabel);
        } else {
            // Jika ada isi, tampilkan list
            jScrollPane2.setViewportView(listDisplay);
        }
    }
    
class PdfConverterWorker extends javax.swing.SwingWorker<String, Integer> {

    private List<File> filesToConvert;
    private String outputPath;

    // 1. Konstruktor: Terima data yang dibutuhkan dari thread utama
    public PdfConverterWorker(List<File> files, String path) {
        // Buat salinan list agar aman dari perubahan
        this.filesToConvert = new ArrayList<>(files); 
        this.outputPath = path;
    }

    // 2. doInBackground(): Ini adalah "MESIN"
    // Berjalan di BACKGROUND THREAD.
    // JANGAN sentuh GUI (progressBar, dll) dari sini!
    @Override
    protected String doInBackground() throws Exception {
        try (PDDocument doc = new PDDocument()) {
            int totalFiles = filesToConvert.size();
            
            for (int i = 0; i < totalFiles; i++) {
                File imageFile = filesToConvert.get(i);
                
                // --- Logika PDFBox Anda ---
                PDImageXObject pdImage = PDImageXObject.createFromFile(imageFile.getAbsolutePath(), doc);
                PDRectangle pageSize = new PDRectangle(pdImage.getWidth(), pdImage.getHeight());
                PDPage page = new PDPage(pageSize);
                doc.addPage(page);
                
                try (PDPageContentStream contentStream = new PDPageContentStream(doc, page)) {
                    contentStream.drawImage(pdImage, 0, 0, pdImage.getWidth(), pdImage.getHeight());
                }
                // --- Selesai logika PDFBox ---
                
                // 3. KIRIM PROGRESS: Hitung persentase dan kirim ke GUI
                int progress = (int) (((double) (i + 1) / totalFiles) * 100);
                publish(progress); // Ini akan memicu method process()
            }
            
            doc.save(outputPath);
            
            // 4. KIRIM HASIL: Kirim pesan sukses
            return "Conversion Success!\nPDF saved in: " + outputPath;
            
        } catch (Exception e) {
            e.printStackTrace();
            // 4. KIRIM HASIL: Kirim pesan error
            return "Error: An error occured during conversion:\n" + e.getMessage();
        }
    }

    // 5. process(): Ini untuk UPDATE GUI
    // Berjalan di GUI THREAD. Aman sentuh GUI.
    // Dipanggil setiap kali 'publish()' dieksekusi.
    @Override
    protected void process(List<Integer> chunks) {
        // Ambil progress TERBARU yang dikirim
        int latestProgress = chunks.get(chunks.size() - 1);
        progressBar.setValue(latestProgress); // Update JProgressBar
    }

    // 6. done(): Ini untuk PEMBERSIHAN
    // Berjalan di GUI THREAD.
    // Dipanggil SETELAH doInBackground() selesai (baik sukses atau error).
    @Override
    protected void done() {
        try {
            // 7. Ambil HASIL dari doInBackground()
            String result = get(); // 'get()' mengambil return value
            
            // 8. Tampilkan hasil (sukses atau error)
            if (result.startsWith("Error:")) {
                JOptionPane.showMessageDialog(MainFrame.this, result, "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(MainFrame.this, result, "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            // Ini menangkap error dari SwingWorker-nya sendiri
            e.printStackTrace();
            JOptionPane.showMessageDialog(MainFrame.this, 
                    "Internal error on worker: " + e.getMessage(), 
                    "Worker Error", 
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            // 9. BERSIH-BERSIH: APAPUN YANG TERJADI...
            // Aktifkan lagi semua tombol
            convertBtn.setEnabled(true);
            addFileBtn.setEnabled(true);
            deleteFileBtn.setEnabled(true);
            upBtn.setEnabled(true);
            downBtn.setEnabled(true);
            outputSetBtn.setEnabled(true);
            listDisplay.setEnabled(true);
            btnClearList.setEnabled(true);
            
            // Reset progress bar
            progressBar.setValue(0);
        }
    }
}
}
