/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zeynconverter;
import com.mycompany.zeynconverter.core.PreferencesService;
import com.mycompany.zeynconverter.conversion.ImgToPdfConverter;
import com.mycompany.zeynconverter.core.ListService;
import com.mycompany.zeynconverter.ui.FileDragHandler;
import java.awt.Desktop;

import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
/**
 *
 * @author Zeyn
 */
public class MainFrame extends javax.swing.JFrame {

    //saving file data
    private DefaultListModel<String> listModel = new DefaultListModel<>();
    private File outputFolder;
    private javax.swing.JLabel emptyListLabel;
    
    //prefs service instance
    private final PreferencesService prefsService = new PreferencesService();
    private final ListService listService = new ListService();
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        listDisplay.setModel(listModel);
        pathTxtArea.setEditable(false);
        pathTxtArea.setLineWrap(true); //make the text wrapped
        pathTxtArea.setWrapStyleWord(true); //make the word wouldn't be cutten
        outputTxtField.setEditable(false);
        //show a friendly warn that there's still nothing added
        emptyListLabel = new javax.swing.JLabel("You are not added anything here :/");
        emptyListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emptyListLabel.setForeground(java.awt.Color.GRAY);
        
        //load the path from prefs service
        String savedPath = prefsService.loadPath();
        this.outputFolder = new File(savedPath);
        outputTxtField.setText(savedPath);
        
        FileDragHandler dragHandler = new FileDragHandler(listService, this);
        listDisplay.setTransferHandler(dragHandler);
        emptyListLabel.setTransferHandler(dragHandler);
        
        
        //GUI list selection listener
        listDisplay.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // check is the change is "final" and is there something selected or not
                if (!e.getValueIsAdjusting()) {
                    int index = listDisplay.getSelectedIndex();

                    if (index != -1) {
                        // There's selected item
                        // get the file from service
                        File choosenFile = listService.getFileAt(index);
                        // show the full path on pathTxtArea
                        if (choosenFile != null){
                            pathTxtArea.setText(choosenFile.getAbsolutePath());
                        }
                    } else {
                        // There's nothing selected (i.e. after deleted)
                        pathTxtArea.setText(""); // clearing pathTxtArea
                    }
                }
            }
        });
        
        updateListView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDisplay = new javax.swing.JList<>();
        appTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pathTxtArea = new javax.swing.JTextArea();
        pathLabel = new javax.swing.JLabel();
        addFileBtn = new javax.swing.JButton();
        deleteFileBtn = new javax.swing.JButton();
        upBtn = new javax.swing.JButton();
        downBtn = new javax.swing.JButton();
        convertBtn = new javax.swing.JButton();
        supportedInfo = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        outputTxtField = new javax.swing.JTextField();
        outputSetBtn = new javax.swing.JButton();
        progressLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        devNote = new javax.swing.JLabel();
        btnClearList = new javax.swing.JButton();
        cbLossless = new javax.swing.JCheckBox();
        btnOpenFolderOutput = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        listDisplay.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listDisplay);

        appTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        appTitle.setText("Zeyn Converter");

        pathTxtArea.setEditable(false);
        pathTxtArea.setColumns(20);
        pathTxtArea.setRows(5);
        jScrollPane3.setViewportView(pathTxtArea);

        pathLabel.setText("File Path");

        addFileBtn.setText("Add File(s)");
        addFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileBtnActionPerformed(evt);
            }
        });

        deleteFileBtn.setText("Delete from List");
        deleteFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFileBtnActionPerformed(evt);
            }
        });

        upBtn.setText("↑");
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });

        downBtn.setText("↓");
        downBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downBtnActionPerformed(evt);
            }
        });

        convertBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        convertBtn.setText("Convert");
        convertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertBtnActionPerformed(evt);
            }
        });

        supportedInfo.setText("*Curently Supported Format: only JPG (.jpg/.jpeg), PNG (.png), and WebP (.webp)");

        outputLabel.setText("Output Folder");

        outputTxtField.setEditable(false);
        outputTxtField.setText("<<Null>>");

        outputSetBtn.setIcon(new javax.swing.ImageIcon("E:\\code_project\\ZeynConverter\\src\\main\\resources\\icons\\create_new_folder_24dp_000000.png")); // NOI18N
        outputSetBtn.setToolTipText("Set Output Folder");
        outputSetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputSetBtnActionPerformed(evt);
            }
        });

        progressLabel.setText("Progress");

        progressBar.setForeground(new java.awt.Color(89, 168, 75));
        progressBar.setStringPainted(true);

        devNote.setText("*On Future Plan Development: SVG (.svg), Bitmap (.bmp, .cur, .ico)");

        btnClearList.setText("Clear List");
        btnClearList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearListActionPerformed(evt);
            }
        });

        cbLossless.setBackground(new java.awt.Color(255, 255, 255));
        cbLossless.setText("Lossless (Size Bigger, Maintain Pixel)");
        cbLossless.setToolTipText("Maintains 100% image quality. Suggested if file size is not a concern.");

        btnOpenFolderOutput.setIcon(new javax.swing.ImageIcon("E:\\code_project\\ZeynConverter\\src\\main\\resources\\icons\\folder_open_24dp_000000.png")); // NOI18N
        btnOpenFolderOutput.setToolTipText("Open Output Folder");
        btnOpenFolderOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFolderOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(devNote)
                                    .addComponent(supportedInfo))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upBtn)
                                    .addComponent(downBtn)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(outputTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outputSetBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpenFolderOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(progressLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbLossless)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(addFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteFileBtn)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnClearList, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pathLabel)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(appTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pathLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addFileBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteFileBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearList)
                        .addGap(44, 44, 44)
                        .addComponent(convertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLossless)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(outputLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(outputTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(outputSetBtn)
                                    .addComponent(btnOpenFolderOutput))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(upBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(downBtn)
                                .addGap(167, 167, 167)))
                        .addComponent(progressLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supportedInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(devNote)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenFolderOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFolderOutputActionPerformed
        // TODO add your handling code here:
        try {
            if(this.outputFolder != null && this.outputFolder.exists()) {
                Desktop.getDesktop().open(this.outputFolder);
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Output folder is not set or does not exist.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(
                this,
                "Could not open folder: \n" + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOpenFolderOutputActionPerformed

    private void btnClearListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearListActionPerformed
        // TODO add your handling code here:
        listService.clearList();
        updateListView();
    }//GEN-LAST:event_btnClearListActionPerformed

    private void outputSetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputSetBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser outputChooser = new JFileChooser();

        //set that JFileChooser only able to choose folder
        outputChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        outputChooser.setDialogTitle("Choose Output Folder");

        int result = outputChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION){
            //get the folder
            File selectedFolder = outputChooser.getSelectedFile();

            //save on outputFolder
            this.outputFolder = selectedFolder;

            //show the path on text field
            outputTxtField.setText(this.outputFolder.getAbsolutePath());

            //saving on prefs service
            prefsService.savePath(this.outputFolder.getAbsolutePath());
        }
    }//GEN-LAST:event_outputSetBtnActionPerformed

    private void convertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertBtnActionPerformed
        // TODO add your handling code here:

        //checking is the list is empty or not
        if (listService.isEmpty()){
            JOptionPane.showMessageDialog(
                this,
                "You are not yet add anything here :/",
                "List is Empty",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        //saving the file use JFileChooser
        JFileChooser saveChooser = new JFileChooser();
        saveChooser.setDialogTitle("Save PDF as...");
        saveChooser.setFileFilter(new FileNameExtensionFilter("PDF Document", "pdf"));

        //check is the output folder was set or not
        if(this.outputFolder != null){
            saveChooser.setCurrentDirectory(this.outputFolder);
        }

        int userSelection = saveChooser.showSaveDialog(this);

        //is user select "Save", not "Cancel"?
        if (userSelection == JFileChooser.APPROVE_OPTION){
            File fileToSave = saveChooser.getSelectedFile();

            //validating file name to ended with .pdf and its path
            String goalPath = fileToSave.getAbsolutePath();
            if(!goalPath.toLowerCase().endsWith(".pdf")){
                goalPath += ".pdf";
            }

            //--- CONVERSION PROCESS---

            //getting the lossy/lossless confirmation
            boolean useLossless = cbLossless.isSelected();

            //disabling all features
            setUIEnabled(false);

            //execute the converter method
            ImgToPdfConverter convert = new ImgToPdfConverter(
                listService.getFiles(),
                goalPath,
                this,
                progressBar,
                useLossless);
            convert.execute();
        }
    }//GEN-LAST:event_convertBtnActionPerformed

    private void downBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downBtnActionPerformed
        // TODO add your handling code here:
        //getting the selected index
        int index = listDisplay.getSelectedIndex();

        listService.moveDown(index);

        updateListView();

        listDisplay.setSelectedIndex(index + 1);
    }//GEN-LAST:event_downBtnActionPerformed

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
        // TODO add your handling code here:
        //getting the selected index
        int index = listDisplay.getSelectedIndex();

        listService.moveUp(index);

        updateListView();

        listDisplay.setSelectedIndex(index - 1);
    }//GEN-LAST:event_upBtnActionPerformed

    private void deleteFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFileBtnActionPerformed
        // TODO add your handling code here:
        //get all selected files
        int[] selectedIndices = listDisplay.getSelectedIndices();

        listService.removeIndices(selectedIndices);
        updateListView();
    }//GEN-LAST:event_deleteFileBtnActionPerformed

    private void addFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setMultiSelectionEnabled(true);

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Gambar (JPG, PNG, WebP)", "jpg", "jpeg", "png", "webp");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION){
            File[] files = fileChooser.getSelectedFiles();

            listService.addFiles(files);
            updateListView();
        }
    }//GEN-LAST:event_addFileBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            // set look and feel to be like OS native view
            javax.swing.UIManager.setLookAndFeel(
                javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
                java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFileBtn;
    private javax.swing.JLabel appTitle;
    private javax.swing.JButton btnClearList;
    private javax.swing.JButton btnOpenFolderOutput;
    private javax.swing.JCheckBox cbLossless;
    private javax.swing.JButton convertBtn;
    private javax.swing.JButton deleteFileBtn;
    private javax.swing.JLabel devNote;
    private javax.swing.JButton downBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listDisplay;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton outputSetBtn;
    private javax.swing.JTextField outputTxtField;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextArea pathTxtArea;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JLabel supportedInfo;
    private javax.swing.JButton upBtn;
    // End of variables declaration//GEN-END:variables
    
    public void updateListView() {
        //clear old data from GUI
        listModel.clear();
        //get new data from service
        List<String> fileNames = listService.getFileNames();
        //input the new data on GUI
        listModel.addAll(fileNames);
        //show empty list if there's none
        if (listModel.isEmpty()) {
            jScrollPane2.setViewportView(emptyListLabel);
        } else {
            jScrollPane2.setViewportView(listDisplay);
        }
    }

    public void setUIEnabled(boolean enabled){
        convertBtn.setEnabled(enabled);
        addFileBtn.setEnabled(enabled);
        deleteFileBtn.setEnabled(enabled);
        upBtn.setEnabled(enabled);
        downBtn.setEnabled(enabled);
        outputSetBtn.setEnabled(enabled);
        btnOpenFolderOutput.setEnabled(enabled);
        listDisplay.setEnabled(enabled);
        btnClearList.setEnabled(enabled);
    }
}
